# This is a boilerplate parameters config generated for pipeline 'classification_pipeline'
# using Kedro 0.18.4.
#
# Documentation for this file format can be found in "Parameters"
# Link: https://kedro.readthedocs.io/en/0.18.4/kedro_project_setup/configuration.html#parameters

process:
  scaler:

model:
  att_block: 'gated'
  input_dim: 2048
  agg_embed_dim: 1024
  cl_hidden_layers_size: [512]
  transformers_first: True

lr_scheduler:
  warmup: 100
  max_iters: 2000

train:
  n_instances: 1000
  train_batch_size: 16
  eval_batch_size: 32
  hyperparameters: {
      'epochs': 30,
      'warmup_epoch': 3,
      'gamma': 0.8,
      'start_lr': 0.00000001,
      'end_lr': 0.00001,
      'positive_weight': 1.1
      }

eval:
  n_instances: 1000